version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ere_250893
    volumes:
      - /c/containers/data:/data/db
    ports:
      - 3306:3306

